---
title: "R Notebook"
author: "Ryan Gan"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

# Plot 2 For Data Incubator Challenge

```{r libraries}
# libraries
library(tidyverse)
library(ncdf4)
library(sf)

# knitr options
knitr::opts_chunk$set(fig.width = 8, fig.height = 6)
```


## Wildfires

Using US Forest Service historic wildfire shape file data and subletting to Colorado from 1980 to 2014.

```{r wildfire_data}
# import wildfires for US
wildfire <- st_read(dsn = "./data/wf_usfs_1980_2016/",
                    layer = "wf_usfs_1980_2016")
# subset to colorado and limit to time period of drought index
co_fires <- wildfire %>% 
  filter(STATE == "Colorado") %>% 
  filter(STARTDATED <= "2014-12-31") %>% 
  filter(Duplicate_ == 0) %>% 
  mutate(Date = lubridate::floor_date(STARTDATED, unit = "months"))

# extract lat lonts
fire_coords <- data.frame(st_coordinates(co_fires)) %>% 
  rename("lon"=X, "lat"=Y) 

# join in with co fires
co_fire_summary <- co_fires %>% 
  bind_cols(fire_coords) %>% 
  group_by(Date) %>% 
  summarise(n_fires = n(), total_acres = sum(TOTALACRES)) %>% 
  mutate(month = factor(months(Date), 
    levels = c("January", "February", "March", "April", "May", "June", "July",
               "August", "September", "October", "November", "December")))

# remove sf geometrey 
st_geometry(co_fire_summary) <- NULL
```

### Plot of Colorado Number of Wildfire Numbers 1980-2014

Plotting number of wildfires of any size by month during the study period. The number of wildfires has been increasing over time for the summer months of June, July, and August.

```{r fire_plot}
# plot
ggplot(co_fire_summary, aes(x=Date, y = n_fires)) +
  geom_point(color = "#b21f1f") +
  geom_smooth(method = "lm", se=F, color = "#243b55") +
  facet_wrap(~month) +
  ylab("Number of Wildfires") +
  ggtitle("Colorado 1980-2014: Number of Wildfires") +
  theme_minimal()
```

